window.SA_DATA = {
  notes: ["茶香", "木质", "花香", "白花", "柑橘", "焚香", "麝香", "琥珀", "绿意", "辛香", "烟草"],
  scenes: [
    { id: "daily", label: "日常通勤" },
    { id: "date", label: "约会" },
    { id: "quiet", label: "安静独处" },
    { id: "gift", label: "送礼" },
    { id: "summer", label: "夏天" },
    { id: "sleep", label: "睡前" }
  ],
  products: [
    {
      id: "vespree",
      brandId: "bienaime",
      brand: "Maison Bienaime",
      name: "Vespree 晚霞之约",
      category: "fragrance",
      country: "France",
      price: 980,
      volume: "75ml",
      concentration: "EDP",
      stock: "现货",
      year: "2026",
      perfumer: "Marie Schnirer",
      family: "木质花香",
      notes: ["木质", "花香", "辛香"],
      scenes: ["daily", "date", "gift"],
      mood: ["warm"],
      sweetness: "medium",
      status: ["New", "买手推荐"],
      image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=82",
      description: "开头有豆蔻、佛手柑和薰衣草的冷亮感，随后转入玫瑰、鸢尾和树脂，像黄昏后空气慢慢变暗。",
      top: "豆蔻、佛手柑、薰衣草、胡萝卜籽",
      middle: "秘鲁香脂、玫瑰、天竺葵、鸢尾",
      base: "香根草、安息香、香草、雪松、檀香",
      buyer: "适合想要一支有礼貌但不普通的通勤花木香。它不是高甜花香，木质和树脂把整体压得更稳。",
      bestFor: "办公室、晚餐、送礼",
      caution: "如果只喜欢非常清爽的柑橘，可能会觉得后调偏暖。"
    },
    {
      id: "ruby-tea",
      brandId: "p-seven",
      brand: "P. Seven",
      name: "Ruby Black Tea 耀香",
      category: "fragrance",
      country: "Taiwan",
      price: 520,
      volume: "66ml",
      concentration: "EDP",
      stock: "现货",
      year: "2024",
      perfumer: "P. Seven Studio",
      family: "东方茶香",
      notes: ["茶香", "木质", "微甜"],
      scenes: ["daily", "gift", "date"],
      mood: ["clean", "warm"],
      sweetness: "medium",
      status: ["Tea", "热卖"],
      image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=82",
      description: "红茶、蜂蜜和蔗糖的温柔甜度被雪松拉住，不会像甜点香那样厚重。",
      top: "蜂蜜、蔗糖",
      middle: "肉桂、茉莉、乌龙茶",
      base: "雪松、柔和麝香",
      buyer: "适合作为小众香水入门茶香。气味亲近、好穿，也有台湾茶香的辨识度。",
      bestFor: "日常、约会、送礼",
      caution: "完全不接受甜感的人建议先试香。"
    },
    {
      id: "oolong-mineral",
      brandId: "one-day",
      brand: "One Day Perfume",
      name: "Oolong Tea 乌龙茶",
      category: "fragrance",
      country: "Thailand",
      price: 720,
      volume: "60ml",
      concentration: "EDP",
      stock: "少量",
      year: "2025",
      perfumer: "One Day Studio",
      family: "清透茶香",
      notes: ["茶香", "柑橘", "麝香"],
      scenes: ["daily", "quiet", "summer"],
      mood: ["clean"],
      sweetness: "low",
      status: ["低甜", "New"],
      image: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=1200&q=82",
      description: "像白瓷杯里刚泡开的乌龙，前段清亮，后段有蜂蜜、茉莉和香根草的淡淡余韵。",
      top: "香柠檬、快乐鼠尾草、乌龙茶叶",
      middle: "蜂蜜、茉莉",
      base: "香根草、东加豆、干净麝香",
      buyer: "不甜、不厚，适合喜欢茶香但怕奶茶感的人。夏天和潮湿天气尤其好穿。",
      bestFor: "通勤、夏天、近距离相处",
      caution: "扩散不强，追求浓烈存在感的人可能会觉得安静。"
    },
    {
      id: "sakura",
      brandId: "satori",
      brand: "Parfum Satori",
      name: "Sakura 樱花",
      category: "fragrance",
      country: "Japan",
      price: 860,
      volume: "50ml",
      concentration: "EDP",
      stock: "现货",
      year: "2023",
      perfumer: "Satori Osawa",
      family: "花香焚香",
      notes: ["花香", "焚香", "麝香"],
      scenes: ["date", "quiet", "gift"],
      mood: ["clean"],
      sweetness: "low",
      status: ["Gift", "柔和"],
      image: "https://images.unsplash.com/photo-1619994403073-2cec844b8e63?auto=format&fit=crop&w=1200&q=82",
      description: "不是甜樱桃，而是轻盈花瓣、粉感麝香和一丝焚香，带有日式留白。",
      top: "樱桃、淡果香",
      middle: "樱花、玫瑰、茉莉",
      base: "焚香、麝香、橡苔、木质",
      buyer: "适合喜欢柔软花香但不想要明显少女甜的人。焚香让它更安静，也更有层次。",
      bestFor: "约会、礼物、春天",
      caution: "喜欢强烈白花或高扩散花香的人可能会觉得偏轻。"
    },
    {
      id: "singha",
      brandId: "siam-1928",
      brand: "Siam 1928",
      name: "Singha 石狮子",
      category: "fragrance",
      country: "Thailand",
      price: 1080,
      volume: "60ml",
      concentration: "Parfum",
      stock: "限量",
      year: "2025",
      perfumer: "Nutt Wesshasartar",
      family: "绿意辛香",
      notes: ["绿意", "辛香", "木质"],
      scenes: ["date", "quiet"],
      mood: ["dark"],
      sweetness: "low",
      status: ["Limited", "收藏"],
      image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=1200&q=82",
      description: "绿竹、高良姜、柿子与橡苔形成潮湿的亚洲植物感，气味有故事，也有力量。",
      top: "高良姜、绿竹、红柿子",
      middle: "绿茶、茉莉、兰花、黄玉兰",
      base: "橡苔、康乃馨、雪松",
      buyer: "适合已经不满足于常见茶香、木质香的人。它有文化叙事，也有绿色辛香的锋利边缘。",
      bestFor: "收藏、晚间、独处",
      caution: "不是大众安全香，建议先试香。"
    },
    {
      id: "incense-rain",
      brandId: "atelier-pluie",
      brand: "Atelier Pluie",
      name: "After Rain 雨后焚香",
      category: "fragrance",
      country: "Korea",
      price: 760,
      volume: "50ml",
      concentration: "Extrait",
      stock: "现货",
      year: "2026",
      perfumer: "J. Moon",
      family: "焚香木质",
      notes: ["焚香", "木质", "水感"],
      scenes: ["quiet", "date", "sleep"],
      mood: ["dark"],
      sweetness: "low",
      status: ["买手推荐"],
      image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=1200&q=82",
      description: "湿木头、寺院烟气和雨后石板，气味低调但有很强的空间感。",
      top: "冷杉、潮湿空气、矿物感",
      middle: "乳香、焚香、纸张",
      base: "雪松、广藿香、麝香",
      buyer: "适合喜欢安静暗色调的人。它不是甜暖焚香，而是更清冷、更湿润。",
      bestFor: "雨天、睡前、独处",
      caution: "如果希望香水明显取悦他人，这支会偏内向。"
    },
    {
      id: "neroli-shirt",
      brandId: "atelier-pluie",
      brand: "Atelier Pluie",
      name: "White Shirt 橙花白衬衫",
      category: "fragrance",
      country: "Korea",
      price: 690,
      volume: "50ml",
      concentration: "EDP",
      stock: "现货",
      year: "2026",
      perfumer: "J. Moon",
      family: "柑橘白花",
      notes: ["柑橘", "白花", "麝香"],
      scenes: ["daily", "summer", "gift"],
      mood: ["clean"],
      sweetness: "low",
      status: ["通勤"],
      image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=1200&q=82",
      description: "橙花、皂感麝香和一点点绿叶，像刚熨好的白衬衫，干净但不单薄。",
      top: "橙花、柠檬、苦橙叶",
      middle: "白花、皂感麝香、绿叶",
      base: "白麝香、轻木质",
      buyer: "非常适合办公室和第一次购买小众香水的人。它清楚、干净，也不会压迫周围人。",
      bestFor: "通勤、夏天、近距离",
      caution: "喜欢浓郁厚重香水的人会觉得它偏轻。"
    },
    {
      id: "library-candle",
      brandId: "bienaime",
      brand: "Maison Candle",
      name: "Library Candle 书房蜡烛",
      category: "home",
      country: "France",
      price: 420,
      volume: "270g",
      concentration: "Candle",
      stock: "现货",
      year: "2026",
      perfumer: "Home Studio",
      family: "空间木质",
      notes: ["木质", "烟草", "琥珀"],
      scenes: ["quiet", "gift"],
      mood: ["warm", "dark"],
      sweetness: "medium",
      status: ["Home"],
      image: "https://images.unsplash.com/photo-1602874801006-e26e3f8f6b81?auto=format&fit=crop&w=1200&q=82",
      description: "旧书页、烟草叶和琥珀树脂，适合把房间变成更安静的阅读空间。",
      top: "纸张、粉尘、黑胡椒",
      middle: "烟草叶、雪松、蜂蜡",
      base: "琥珀、劳丹脂、柔和麝香",
      buyer: "适合作为空间香氛的第一支。它不甜腻，有成熟的木质厚度。",
      bestFor: "书房、卧室、礼物",
      caution: "燃烧时保持通风并远离织物。"
    }
  ],
  brands: [
    {
      id: "satori",
      name: "Parfum Satori",
      country: "Japan",
      founder: "Satori Osawa",
      keywords: ["日本美学", "花香", "焚香", "留白"],
      hero: "https://images.unsplash.com/photo-1619994403073-2cec844b8e63?auto=format&fit=crop&w=1400&q=82",
      intro: "以东方材料和日式留白塑造细腻香气，适合喜欢安静花香、焚香和层次变化的人。",
      story: "品牌作品常常把花香、香料、木质和焚香处理得很克制。它不追求强扩散，而是强调气味在皮肤上的细微转折。",
      starter: "Sakura 樱花"
    },
    {
      id: "p-seven",
      name: "P. Seven",
      country: "Taiwan",
      founder: "P. Seven Studio",
      keywords: ["台湾茶", "日常记忆", "温柔", "入门"],
      hero: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1400&q=82",
      intro: "用台湾茶、城市记忆和轻盈甜度做出容易亲近的小众香水。",
      story: "适合从茶香进入小众香水的人。作品往往有清楚的主题，也保留日常穿着的友好度。",
      starter: "Ruby Black Tea 耀香"
    },
    {
      id: "one-day",
      name: "One Day Perfume",
      country: "Thailand",
      founder: "One Day Studio",
      keywords: ["清透茶香", "热带空气", "低甜", "夏天"],
      hero: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=1400&q=82",
      intro: "以轻盈茶香、柑橘和湿润空气感为主，适合炎热季节和低甜偏好。",
      story: "品牌作品通常不厚重，强调皮肤上的透明感和贴近日常的舒适度。",
      starter: "Oolong Tea 乌龙茶"
    },
    {
      id: "siam-1928",
      name: "Siam 1928",
      country: "Thailand",
      founder: "Nutt Wesshasartar",
      keywords: ["亚洲香料", "文化叙事", "绿意", "收藏"],
      hero: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=1400&q=82",
      intro: "用亚洲植物、香料和历史叙事构建辨识度强的香水。",
      story: "不一定是大众安全香，但很适合已经想探索更鲜明气味语言的人。",
      starter: "Singha 石狮子"
    },
    {
      id: "bienaime",
      name: "Maison Bienaime",
      country: "France",
      founder: "Maison Bienaime",
      keywords: ["法式复古", "花香", "树脂", "礼物"],
      hero: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1400&q=82",
      intro: "复古瓶身、柔软花木和法式礼物感，适合寻找精致但不过分甜腻的香水。",
      story: "品牌更适合作为礼物和第一支正式小众香水，整体风格温柔、端正、有包装完成度。",
      starter: "Vespree 晚霞之约"
    },
    {
      id: "atelier-pluie",
      name: "Atelier Pluie",
      country: "Korea",
      founder: "J. Moon",
      keywords: ["雨天", "清冷", "焚香", "通勤"],
      hero: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=1400&q=82",
      intro: "以雨后空气、纸张、白衬衫和清冷焚香做出安静的现代感。",
      story: "适合喜欢低扩散、清洁感和湿润木质的人。香气不吵，但有细节。",
      starter: "White Shirt 橙花白衬衫"
    }
  ],
  sampleSets: [
    {
      id: "starter-sample",
      name: "新客发现试香套装",
      price: 168,
      volume: "6 x 1.5ml",
      notes: ["茶香", "木质", "花香", "麝香", "焚香", "柑橘"],
      image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1200&q=82",
      intro: "覆盖六个入门方向，适合第一次购买小众香水的人。",
      bestFor: "还不知道自己喜欢什么、想建立气味坐标的新客",
      products: ["ruby-tea", "oolong-mineral", "vespree", "sakura", "incense-rain", "neroli-shirt"]
    },
    {
      id: "tea-sample",
      name: "茶香主题试香套装",
      price: 198,
      volume: "4 x 1.5ml",
      notes: ["乌龙", "红茶", "焙茶", "花茶"],
      image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=82",
      intro: "从清透乌龙到温柔红茶，适合低甜度和东方感偏好。",
      bestFor: "喜欢茶、白衬衫、木质和安静扩散的人",
      products: ["ruby-tea", "oolong-mineral"]
    },
    {
      id: "wood-sample",
      name: "木质与焚香试香套装",
      price: 218,
      volume: "4 x 1.5ml",
      notes: ["雪松", "檀香", "焚香", "烟草"],
      image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=1200&q=82",
      intro: "偏冷感、雨天和树脂质地，适合想找更成熟气味的人。",
      bestFor: "喜欢安静木头、寺院烟气、旧书页的人",
      products: ["vespree", "incense-rain", "library-candle"]
    }
  ],
  edits: [
    {
      id: "tea-edit",
      title: "茶香季",
      eyebrow: "Tea note",
      intro: "乌龙、红茶和焙茶方向，低甜、清爽、有余韵。",
      href: "shop.html?note=茶香",
      image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=82"
    },
    {
      id: "office-edit",
      title: "干净通勤",
      eyebrow: "Office",
      intro: "低扩散、干净、可近距离相处，不会占满电梯和会议室。",
      href: "shop.html?scene=daily",
      image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=1200&q=82"
    },
    {
      id: "wood-edit",
      title: "雨天木质",
      eyebrow: "Rain wood",
      intro: "湿木头、纸张、树脂和焚香，适合安静独处。",
      href: "shop.html?note=木质",
      image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=1200&q=82"
    }
  ],
  articles: [
    {
      id: "first-niche",
      category: "Letter",
      title: "写给第一次认真闻香水的人",
      date: "2026-05-01",
      image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1400&q=82",
      excerpt: "从茶香、麝香、柑橘和干净木质开始，慢慢建立自己的气味清单。",
      body: [
        "第一次买小众香水，不建议直接从最浓烈、最抽象的作品开始。茶香、干净麝香、轻柑橘和纸感木质通常更容易进入，也更容易在日常穿着。",
        "如果你担心盲买出错，先用试香套装建立自己的气味坐标。记录你喜欢的是清爽、粉感、烟感、甜感还是木质干燥感。",
        "真正适合你的香水，不一定是前调最惊艳的那支，而是三小时后你仍然愿意闻到的那支。"
      ],
      relatedProducts: ["ruby-tea", "oolong-mineral", "neroli-shirt"]
    },
    {
      id: "clean-wood",
      category: "Review",
      title: "木质香不一定沉重：5 款干净木质调推荐",
      date: "2026-04-24",
      image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=1400&q=82",
      excerpt: "纸张、雪松、檀木和矿物感，让木质香也可以轻盈。",
      body: [
        "很多人以为木质香一定厚重、成熟或者有强烈烟草感，其实纸张、雪松和浅檀香也可以非常干净。",
        "如果你在办公室使用，优先选择低扩散、低甜度、后调稳定的木质香。它们不会强迫别人注意到你，但会在近距离留下清楚印象。"
      ],
      relatedProducts: ["vespree", "incense-rain", "library-candle"]
    },
    {
      id: "summer-tea",
      category: "Season",
      title: "适合夏天的茶香香水",
      date: "2026-04-18",
      image: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=1400&q=82",
      excerpt: "低甜、清爽、有余韵，适合潮湿天气和近距离相处。",
      body: [
        "夏天的茶香重点不是甜，而是清透和耐闻。乌龙、白茶和轻红茶都适合高温天气。",
        "如果茶香里有明显奶感或糖感，夏天可能会显得厚。低甜茶香更像干净衣物和温热皮肤之间的距离。"
      ],
      relatedProducts: ["ruby-tea", "oolong-mineral"]
    }
  ]
};
